### PR TITLE
[FilterStepForm] Fix :: Set column value with current selected column

### PR DESCRIPTION
**Pull request by Dalanir**
closes # #300

### CODE REVIEW

**Comment by adimascio** [comment]
@Dalanir I've pushed a commit as an update proposal to:

- fix the tests,
- add a comment to the `mounted()` logic

**Comment by Dalanir** [comment]
@adimascio Thank you, seems good to me if you want to submit it to review or review it yourself too !

**Comment by adimascio** [comment]
> @Dalanir @adimasci beware this implementation introduces a bug:
> => The filtered column is now `Column2` and not `Column1` which is not expected.

Should be fixed now, thanks!

**Comment by Dalanir** [comment]
LGTM too !

**Pull request merged**
